# Generated by Django 4.2.29 on 2026-03-10 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_servicemodel_cataloguemodel_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cataloguemodel',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogues', to='products.servicemodel'),
        ),
    ]
