# Generated by Django 4.2.29 on 2026-04-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='description_two',
            field=models.TextField(blank=True, null=True),
        ),
    ]
