# Generated by Django 4.2.29 on 2026-04-12 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productmodel_description_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cataloguemodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='description_two',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description_conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description_intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cataloguemodel',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service', to='products.servicemodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogue', to='products.cataloguemodel'),
        ),
    ]
